### ISSUE TITLE
Changing to another caferteria => not saved

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-iOS#222]
Userfeedback:
"Changing to the another Cafeteria is not saved.

When tipping on the Cafeteria item and changing the Cafeteria, e.g from Arcisstr to Garching, this only changes the detail view. 
So after changing the Cafeteria, it changes in the current view. But when you go back to the overview, the Cafeteria didn't change (so it stays on Arcisstr). This is also true, if you select Cafeteria a second time. Then also Arcisstr is selected and displayed. "

**Comment by mathiasquintero** [comment]
Right now we're always choosing the one closest to the user's current location.
This poses a couple of questions. 

Are we supposed to change this behavior entirely?
Always show the last selected? 
Even after killing the app?
When should we show the user the one that's the closest? Because that's one of my favorite features.

**Comment by kordianbruck** [comment]
So actually it would be better to choose the Mensa based on their next lecture. But in any case one should offer an override for this "smart" detection

**Comment by thellmund** [comment]
Related to #35. Update according to default campus the user selects in the app.

**Comment by TG908** [comment]
no longer applicable due to app rewrite
