### ISSUE TITLE
Mensa Tab broken

### ISSUE THREAD

**Issue by tgymnich** [TUM-Dev/Campus-iOS#385]
API has changed again ...

`Dish.ingredients` is now optional.

**Comment by NikolaiMadlener** [comment]
working on it

**Comment by Philipp000** [comment]
We have now switched to a variant with `labels` instead of `ingredients` in the eat-api.
The explanations are now also available via `enums/labels.json` (https://tum-dev.github.io/eat-api/enums/labels.json)

Further, there will be a few additional changes, such as including english translations (https://github.com/TUM-Dev/eat-api/pull/87) and abbreviations (for easier references, https://github.com/TUM-Dev/eat-api/pull/85).
I can also take care of the changes in the TUM-Campus App once these changes are merged and Live.

**Comment by NikolaiMadlener** [comment]
Thanks @Philipp000, good to know that you will also provide abbreviations etc. as I already started implementing that inside the App 😅 I guess I'll wait a bit until the those things are merged within the API :)

**Comment by Philipp000** [comment]
Ah okay, yeah i hope that it will be merged very soon.
If you have any other ideas for the eat-api feel free to add them, as probably other applications can benefit from it as well!  :)

**Comment by Philipp000** [comment]
What is the state of this issue?
I would like to work on this, if possible.

**Comment by NikolaiMadlener** [comment]
I have not managed to look at it yet so feel free to go ahead :)

**Comment by AW-tum** [comment]
No issues since version 4.0
